---
- name: install apache
  yum:
    name: "{{ item }}"
  with_items:
    - httpd
    - httpd-tools

- name: add deploy user into apache group
  user:
    groups: apache
    name: "{{ roles_common_deploy_user }}"

- name: set permissions for Apache on application root
  file:
    path: "/home/{{ roles_common_deploy_user }}"
    state: directory
    owner: "{{ roles_common_deploy_user }}"
    group: apache
    mode: 0710

- name: set umask to add writable permission for apache group users
  lineinfile:
    path: /etc/sysconfig/httpd
    line: umask 002

- name: enable service on boot
  service:
    name: httpd
    enabled: yes

- name: set logrotate as daily
  blockinfile:
    path: /etc/logrotate.d/httpd
    insertafter: ^\s*endscript$
    block: |
      daily
